FROM nvim-env:base

RUN curl -fLo ${home}/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

RUN apt-get install -y bat && \
    if [ ! -d ${home}/.local/bin ]; then \
        mkdir -p ${home}/.local/bin; \
    fi && \
    ln -sf /usr/bin/batcat ${home}/.local/bin/bat
